---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.test-flux: semver:~1.0
  name: preprod-helloworld
  namespace: preprod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: helloworld
      containers:
      - image: particule/helloworld:3.0
        name: helloworld
